[package]
name = "ntree"
version = "0.1.0"
authors = ["Jacob Wahlgren <jacob.wahlgren@gmail.com>"]
license = "MPL-2.0"

[[bin]]
name = "ntree"
doc = false

[dependencies]
clap = "2"
globset = "0.1"

[dependencies.git2]
version = "0.5"
# We don't need network features
default-features = false
